{% extends 'admin/layout.phtml' %}
{% block slidebar %} {% include 'admin/slidebar.phtml' %}{% endblock %}
{% block content %}
<section id="main" class="column">
		
	<!-- <h4 class="alert_info">Welcome to the free MediaLoot admin panel template, this could be an informative message.</h4> -->
	
	<article class="module width_full">
		<header><h3 class="tabs_involved">Baby Search</h3>
		<ul class="tabs">
		<!-- 
			<li><a class="change-status" href="javascript:void(0);">變更開通狀態</a></li>
			<li>|</li>
		 -->
			<li>
				<a href="/admin/add_bulletin">新增</a>
			</li>
		</ul>
		
		<ul class="tabs" style="margin-top:5px;margin-left:200px;">
			<li>
				<a href="/admin/device/{{ page-1 }}">&lt前一頁</a>
			</li>
			<li>|</li>
			<li><a href="/admin/device/{{ page+1 }}">後一頁></a></li>
		</ul>
		</header>

		<div class="tab_container">
			<div id="tab1" class="tab_content">
			<table class="tablesorter" cellspacing="0"> 
			<thead> 
				<tr> 
					<th>新增日期</th> 
					<th>公告內容</th> 
					<th>狀態</th> 
					<th>上/下架</th>
					<th>推播至手機</th>
					<th>移除</th> 			
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
				</tr> 
			</thead>
			<tbody>
				{% if list|length > 0 %}
				{% for l in list %}
				<tr> 
					<td>{{ l.created }}</td> 
					<td><a class="imei_code ellipsis" href="/admin/edit_bulletin/{{ l.id }}" title="{{ l.id }}">{{ l.message }}</a>
					</td> 
					<td>
						<p class="table-content ellipsis">
						{% if l.status == 'normal' %}
						{{ '上架中' }}
						{% else %}
						{{ 'N/A' }}
						{% endif %}
						</p>
					</td> 
					<td>
						<p class="imei_code ellipsis">
						{% if l.display == 'y' %}
						<a href="/admin/toggle_bulletin/{{l.id}}"><font style="color:blue;margin-left:15px;">{{ '上架' }}</font></a>
						{% else %}
						<a href="/admin/toggle_bulletin/{{l.id}}"><font style="color:red;margin-left:15px;">{{ '下架' }}</font>
						{% endif %}
						</p>
					</td>
					<td>
						<p class="table-content ellipsis">
						{% if l.push == 'Enable' %}
						<a href=""><font style="color:blue;margin-left:10px;">{{ l.push }}</font></p></a>
						{% elseif l.push == 'Disable' %}
						<a href=""><font style="color:blue;margin-left:10px;">{{ l.push }}</font></p></a>
						{% else %}
						<a href=""><font style="color:blue;margin-left:10px;">推播</font></p></a>
						{% endif %}
					</td>
					<td>
						<a href="/admin/delete_bulletin/{{l.id}}"><div style="background:transparent;"><p class="table-content ellipsis"><font style="color:red;margin-left:10px;"><strong>X</strong></font></p></div></a>
					</td>
					<td>
					</td>
					<td>
					</td> 
					<td>
					</td>
					<!-- 
					<td>
						<p class="table-content ellipsis">
							{% set register = l.register_status == 'disable' ? '未註冊' : '已註冊' %}
							{{ register }}
						</p>
					</td>
					<td>
						{% if l.service_status == 'active' %}
						<p class="table-content green ellipsis">SIM卡使用中</p>
						{% elseif l.service_status == 'expired' %}
						<p class="table-content red ellipsis">SIM卡服務過期</p>
						{% endif %}
					</td>
					<td>
						{% if l.active_status == 'inactive' %}
						<p class="table-content ellipsis">未開通</p>
						{% elseif l.active_status == 'pending' %}
						<p class="table-content yellow ellipsis">等待開通</p>
						{% elseif l.active_status == 'active' %}
						<p class="table-content green ellipsis">開通保固中</p>
						{% elseif l.active_status == 'expired' %}
						<p class="table-content red ellipsis">保固過期</p>
						{% endif %}
					</td> 
					 -->
					<!-- <td><input type="image" src="../public/img/admin/icn_edit.png" title="Edit"></td> -->
				</tr>
				{% endfor %}
				{% else %}
				<tr><td colspan="13" style="text-align:center;">尚無資訊</td></tr>
				{% endif %}
			</tbody>
			 <!-- 
			<thead> 
				<tr> 
					<th>No.</th> 
					<th><input class="choice-all" type="checkbox" ></th> 
					<th>IMEI</th> 
					<th>經銷商</th> 
					<th>購買人</th> 
					<th>性別</th>
					<th>地址</th>
					<th>手機號碼</th>
					<th>Email</th>
					<th>註冊狀態</th>
					<th>SIM卡服務狀態</th>
					<th>開通狀態</th>
					<th></th>
				</tr> 
			</thead> 
			<tbody>
				{% if list|length > 0 %}
				{% for l in list %}
				<tr> 
					<td>{{ loop.index }}.</td> 
					<td>
						{% if l.active_status == 'pending' %}
						<input class="choice" type="checkbox" value="{{ l.imei_code }}">
						{% endif %}
					</td>
					<td><a class="imei_code ellipsis" href="/admin/product/{{ l.imei_code }}" title="{{ l.imei_code }}">{{ l.imei_code }}</a></td> 
					<td>
						<p class="table-content ellipsis" title="{{ l.dealer_name }}">{{ l.dealer_name }}</p>
					</td> 
					<td>
						<p class="table-content ellipsis" title="{{ l.name }}">{{ l.name }}</p>
					</td>
					<td>
						<p class="table-content ellipsis">
							{% set gender = l.gender == 'male' ? '男' : '女' %}
							{{ gender }}
						</p>
					</td>
					<td>
						<p class="table-content ellipsis" title="{{ l.zipcode }} {{ l.address }}">{{ l.zipcode }} {{ l.address }}</p>
					</td>
					<td>
						<p class="table-content ellipsis" title="{{ l.phone }}">{{ l.phone }}</p>
					</td>
					<td>
						<p class="table-content ellipsis" title="{{ l.email }}">{{ l.email }}</p>
					</td>
					<td>
						<p class="table-content ellipsis">
							{% set register = l.register_status == 'disable' ? '未註冊' : '已註冊' %}
							{{ register }}
						</p>
					</td>
					<td>
						{% if l.service_status == 'active' %}
						<p class="table-content green ellipsis">SIM卡使用中</p>
						{% elseif l.service_status == 'expired' %}
						<p class="table-content red ellipsis">SIM卡服務過期</p>
						{% endif %}
					</td>
					<td>
						{% if l.active_status == 'inactive' %}
						<p class="table-content ellipsis">未開通</p>
						{% elseif l.active_status == 'pending' %}
						<p class="table-content yellow ellipsis">等待開通</p>
						{% elseif l.active_status == 'active' %}
						<p class="table-content green ellipsis">開通保固中</p>
						{% elseif l.active_status == 'expired' %}
						<p class="table-content red ellipsis">保固過期</p>
						{% endif %}
					</td> 
					--><!-- <td><input type="image" src="../public/img/admin/icn_edit.png" title="Edit"></td> 
				</tr>
				{% endfor %}
				{% else %}
				<tr><td colspan="13" style="text-align:center;">尚無資訊</td></tr>
				{% endif %}
			</tbody> 
			-->
			</table>
			</div><!-- end of #tab1 -->
		</div><!-- end of .tab_container -->
	</article><!-- end of content manager article -->
	<div class="spacer"></div>
</section>
{% if flash.import_msg is defined %}
<script>
alert('{{ flash.import_msg }}');
</script>
{% endif %}
{% if flash.toggle_bulletin_success is defined %}
<script>
alert('{{ flash.toggle_bulletin_success }}');
</script>
{% endif %}
{% if flash.toggle_bulletin_error is defined %}
<script>
alert('{{ flash.toggle_bulletin_error }}');
</script>
{% endif %}

{% endblock %}
