<!DOCTYPE html>
<html lang="zh-tw">
<head>
	<meta charset="utf-8">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="expires" content="0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=2.0,user-scalable=yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<meta http-equiv="Content-Language" content="zh-tw">
	{% if page_name is defined %}
	<title> {{ page_name }} - iPet 愛寵 </title>
	{% else %}
	<title> iPet 愛寵 </title>
	{% endif %}
	<link rel="icon" href="/favicon.jpg" type="image/x-icon">
	<link rel="shortcut icon" href="/favicon.jpg" type="image/x-icon">
	<link rel="stylesheet" href="/public/css/main.css" type="text/css" media="screen">
	{% block css %}{% endblock %}
</head>
<body>
	{% set l = locale_text %}
	<header id="header" class="clearfix">
		<a href="http://www.ipet-tracker.com">
			<img class="header--logo" id='logo' src='/public/img/logo.png'/>
		</a>
		{% if login == true %}
		<a class="header--logout" href="/logout">{{ l.LOG_OUT }}</a>
		{% endif %}
	</header>
	<main id="main">
		<div class="container">
			{% block content %}{% endblock %}
		</div>
	</main>
	<footer id='footer'>
		&copy; {{ 'now'|date('Y') }} {{ l.Tracker_Technology }}
	</footer>
<script>
	var csrf_key = '{{ csrf_key }}';
	var csrf_token = '{{ csrf_token }}';
</script>
<script src="//code.jquery.com/jquery.min.js"></script>
<script src='//cdn.jsdelivr.net/jquery.form/3.50/jquery.form.min.js'></script>
<script src='//cdn.jsdelivr.net/jquery.blockui/2.65.0/jquery.blockUI.min.js'></script>
<script src='/public/js/default.js'></script>
{% block js %}{% endblock %}
</body>
</html>